columnSuffix: null
handle: fourPictures
instructions: null
name: 'Négy kép'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds: null
  branchLimit: null
  defaultPlacement: end
  defaultUploadLocationSource: 'volume:33fbdc92-4491-48e7-a475-1e1fdf3fc897' # Képek
  defaultUploadLocationSubpath: null
  maintainHierarchy: false
  maxRelations: 4
  minRelations: 4
  previewMode: full
  restrictFiles: false
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:33fbdc92-4491-48e7-a475-1e1fdf3fc897' # Képek
  restrictedLocationSubpath: null
  selectionLabel: null
  showCardsInGrid: false
  showSearchInput: true
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: none
type: craft\fields\Assets
