columnSuffix: null
handle: simpleText
instructions: null
name: Sz√∂veg
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 1
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
