dateModified: 1762586222
email:
  fromEmail: fulop.viktor.dwiki@gmail.com
  fromName: parkhedervar
  transportType: craft\mail\transportadapters\Sendmail
fs:
  kepek:
    hasUrls: true
    name: Képek
    settings:
      path: '@webroot/images'
    type: craft\fs\Local
    url: /images
  sliderPictPlace:
    hasUrls: true
    name: 'Képváltó képek helye'
    settings:
      path: '@webroot/sliderimages'
    type: craft\fs\Local
    url: /sliderimages
graphql:
  publicToken:
    enabled: false
    expiryDate: null
meta:
  __names__:
    0a8824d5-d531-40bc-b0c8-c420edc4449b: Német # Német
    1ddf3471-9514-416a-8cdd-cb453f093e39: 'Szöveges dokumnetum -  heti menu' # Szöveges dokumnetum -  heti menu
    2bc467f8-64cd-4784-be94-b76f3f1d7fc4: 'Kép / PDF' # Kép / PDF
    2bd5267e-a36c-43fa-96fd-e740550c69fc: Nyitólap # Nyitólap
    2f53b4bd-d51b-42f6-bcc4-3e47dbe60815: HÍrek # HÍrek
    3f01429d-2635-4f6a-a7e2-03296a05e255: Nyitó # Nyitó
    4cb3f0fe-5a28-46e4-aeca-af520ddf4746: Kapcsoló # Kapcsoló
    5b557374-743e-40fc-8528-a0d4e9b40506: 'Képváltó képek' # Képváltó képek
    5fea41c4-9177-4d44-928a-27f69f223cc0: Tartalom # Tartalom
    7abe536e-08e9-4ec4-bf82-1ac522ea4f84: Hírek # Hírek
    8bcb174f-c2de-46c2-b796-1394dac78109: Cikk # Cikk
    8d411e5c-39cc-4ade-9676-74c2aae7bcf9: Fejléc # Fejléc
    8ea3f70c-70e2-469a-945b-53ac9e122b75: Adatok # Adatok
    29c80c0b-78ca-43dd-b83a-44f42bf35cd6: 'Nyitólap - one page' # Nyitólap - one page
    33fbdc92-4491-48e7-a475-1e1fdf3fc897: Képek # Képek
    36f675c9-3455-4876-b913-6b88042286a0: 'Heti menü' # Heti menü
    88c6398a-f683-42af-9840-82a752943ecc: Főmenü # Főmenü
    493d156c-cec2-48a1-8873-4db0e47f5d35: 'Kép és szöveg' # Kép és szöveg
    785c09ff-d241-42d1-b0a7-c985a24a712c: Bejegyzések # Bejegyzések
    846aa6c1-3a4b-4656-a534-646aa812d4f4: Simple # Simple
    915fda05-fe2f-4d16-8676-0d5f34b33d08: Adat # Adat
    939c7f22-e6c5-4dbe-8aaa-69b6c587edd0: 'Basic dw' # Basic dw
    02980df4-89da-41dc-9c95-0b95a8764e23: Menü # Menü
    5032b9b8-3c3f-4bd9-b66c-9b616eabab4c: Popup # Popup
    6652c4a0-b521-4514-9e6a-ba6383a6325a: 'Szöveg doboz' # Szöveg doboz
    8792f1cf-e9e4-4f28-9777-8c5304780529: 'Egy kép' # Egy kép
    15374a4b-7c57-4349-9965-a0cfda75df3f: 'Négy kép' # Négy kép
    36685e5a-d503-4f86-9d6d-e73a0d97dc93: 'Képváltó képek' # Képváltó képek
    94625fe0-14e2-4fe2-94d5-d0d88b34013a: parkhedervar # parkhedervar
    a0ed06e8-7d19-46e7-b39f-32af2d4e18c3: Sebesség # Sebesség
    b3a9b4f6-0a54-40c7-80fa-8a53361137e2: Választó # Választó
    bb5ef826-a820-4982-a272-9ad7d3c5be5a: parkhedervar # parkhedervar
    becc6248-77f7-4548-9c0c-9326b0764e28: HÍr # HÍr
    cd5eaea5-24c1-47f6-96bf-ce456bbed2f2: Cikkek # Cikkek
    d7bf11f6-03cd-4651-b906-363634efd7dd: Hír # Hír
    d11f6ee6-67d9-4ae4-8924-e8dffc44555a: Szöveg # Szöveg
    d823c0fc-0e81-4d86-95cf-0b55ac23463e: 'Kép és szöveg' # Kép és szöveg
    d46898f6-87ca-4eea-ae8d-1c1f76206e53: Kategória # Kategória
    e0fa9cd2-ed5d-4928-999a-9131fd0788fb: Lábléc # Lábléc
    efcb092e-4d8f-429a-aca8-d3806c9f7df2: 'Nagy kép - szöveg' # Nagy kép - szöveg
    fbc0eba2-1bc3-4182-8660-1c571425c373: '4 kép + szöveg blokk' # 4 kép + szöveg blokk
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  dwiki-form2:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      i18n:
        __assoc__:
          -
            - 0a8824d5-d531-40bc-b0c8-c420edc4449b # Német
            -
              __assoc__:
                -
                  - recipientEmail
                  - ''
                -
                  - modalTitle
                  - ''
                -
                  - modalMessage
                  - ''
          -
            - bb5ef826-a820-4982-a272-9ad7d3c5be5a # parkhedervar
            -
              __assoc__:
                -
                  - recipientEmail
                  - fulop.viktor.dwiki@gmail.com
                -
                  - modalTitle
                  - 'Köszönjük üzenetét!'
                -
                  - modalMessage
                  - 'Hamarosan felvesszük Önnel a kapcsolatot.'
      modalMessage: null
      modalTitle: null
      recipientEmail: null
system:
  edition: solo
  live: true
  name: parkhedervar
  schemaVersion: 5.8.0.3
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
