fieldLayouts:
  cf3f0b4a-17b0-4858-8b00-01f33a41dfbf:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-11-02T11:51:48+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8792f1cf-e9e4-4f28-9777-8c5304780529 # Egy kép
            handle: null
            includeInCards: false
            instructions: null
            label: Logo
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e4cd7b2c-b185-4845-b418-baf69bfad0f8
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-11-02T11:51:48+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6652c4a0-b521-4514-9e6a-ba6383a6325a # Szöveg doboz
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 13d68972-2b6b-4922-9dbb-cf1f6994818b
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-11-02T11:51:48+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6652c4a0-b521-4514-9e6a-ba6383a6325a # Szöveg doboz
            handle: textBox2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 970a9d49-d840-47a7-8a41-1745d7210483
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-11-02T11:51:48+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6652c4a0-b521-4514-9e6a-ba6383a6325a # Szöveg doboz
            handle: textBox3
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 759ce8c2-1bc2-4ac7-886c-793faf22cf8f
            userCondition: null
            warning: null
            width: 100
        name: Tartalom
        uid: 96744896-de04-4889-911c-7a1e5b251703
        userCondition: null
handle: footer
name: Lábléc
sortOrder: 4
