fieldLayouts:
  17274281-79ad-44dc-bd0d-be006aeef46c:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-10-10T17:23:11+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d11f6ee6-67d9-4ae4-8924-e8dffc44555a # Szöveg
            handle: menuTitle
            includeInCards: false
            instructions: null
            label: Cím
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 39f90362-1a34-4efc-b4ea-5fa3f7414aec
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-10T17:23:11+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1ddf3471-9514-416a-8cdd-cb453f093e39 # Szöveges dokumnetum -  heti menu
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9dcf8ff1-e2ac-43a1-ad43-7f3fb1f456a5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-10T17:23:11+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 2bc467f8-64cd-4784-be94-b76f3f1d7fc4 # Kép / PDF
            handle: menuAttachment
            includeInCards: false
            instructions: 'Letölthető étlap kép vagy pdf formában'
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 633834a4-dc91-4e90-a827-361156d2e4a7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-02T10:49:40+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6652c4a0-b521-4514-9e6a-ba6383a6325a # Szöveg doboz
            handle: null
            includeInCards: false
            instructions: 'Általános szöveg a menühöz, állandó menük.'
            label: 'Általános szöveg'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 45ed36fb-66a7-462a-962b-d3d48b00400a
            userCondition: null
            warning: null
            width: 100
        name: Tartalom
        uid: 3365a352-4618-4309-93bf-456d32855c56
        userCondition: null
handle: weeklyMenu
name: 'Heti menü'
sortOrder: 3
