defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: d7bf11f6-03cd-4651-b906-363634efd7dd # Hír
handle: newsStart
maxAuthors: 1
name: HÍrek
previewTargets:
  -
    label: 'Elsődleges bejegyzés oldal'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  0a8824d5-d531-40bc-b0c8-c420edc4449b: # Német
    enabledByDefault: true
    hasUrls: true
    template: news.twig
    uriFormat: hirek
  bb5ef826-a820-4982-a272-9ad7d3c5be5a: # parkhedervar
    enabledByDefault: true
    hasUrls: true
    template: news.twig
    uriFormat: hirek
type: single
